Update grid.py
Traceback (most recent call last):
  File "/Users/angelikaanette/Documents/Coding/Ballzoom-project/Ballzoom/test_videos/Ballzoom.py", line 110, in <module>
    main()
  File "/Users/angelikaanette/Documents/Coding/Ballzoom-project/Ballzoom/test_videos/Ballzoom.py", line 12, in main
    heat(sys.argv[1])
  File "/Users/angelikaanette/Documents/Coding/Ballzoom-project/Ballzoom/test_videos/Ballzoom.py", line 32, in heat
    ffmpeg
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ffmpeg/_run.py", line 313, in run
    process = run_async(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ffmpeg/_run.py", line 280, in run_async
    args = compile(stream_spec, cmd, overwrite_output=overwrite_output)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ffmpeg/_run.py", line 190, in compile
    return cmd + get_args(stream_spec, overwrite_output=overwrite_output)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ffmpeg/_run.py", line 161, in get_args
    filter_arg = _get_filter_arg(filter_nodes, outgoing_edge_maps, stream_name_map)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ffmpeg/_run.py", line 101, in _get_filter_arg
    _allocate_filter_stream_names(filter_nodes, outgoing_edge_maps, stream_name_map)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ffmpeg/_run.py", line 90, in _allocate_filter_stream_names
    raise ValueError(
ValueError: Encountered scale(force_original_aspect_ratio='increase', size='hd1080') <1c0ba3a7069b> with multiple outgoing edges with same upstream label None; a `split` filter is probably required